sudo: required
services:
    - docker

before_install:
    - docker build -t brianngo313/udemy-docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true brianngo313/udemy-docker-react npm run test
